inputs:
   - name     : ${HOME}/data/eviz/mopitt/MOP03JM-202205-L3V95.6.3.he5
   - description: Global map of MOPITT column CO
     to_plot  :
         RetrievedCOTotalColumnDay: xy

outputs:
    output_dir: ${HOME}/scratch/eviz/output/mopitt
    print_to_file: yes
    print_format: png

  
