inputs:
   - name  : ${HOME}/data/eviz/lis/day11/LIS_HIST_20150711*
     exp_id: file1
     to_plot  :
        AvgSurfT_tavg: xt

   - name  : ${HOME}/data/eviz/lis/day12/LIS_HIST_20150712*
     exp_id: file2
     to_plot  :
        AvgSurfT_tavg: xt

outputs:
    output_dir: ${HOME}/scratch/eviz/output/lis_xt_compare
    print_to_file: yes

for_inputs:
    compare:
      ids: file1,file2

