inputs:
   - name         : /Users/vvalenti/data/satellite_data/OMI-Aura_L3-OMTO3e_2022m0709_v003-2022m0711t031807.he5
    #  location     : /discover/nobackup/projects/jh_tutorials/eviz/sample_data/ccm/Benchmark_F_c180/tavg24_3d_dat_Np
     exp_name    : BenchmarkFc180