name: viz
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - xesmf >=0.7.1
  - matplotlib >=3.8.2
  - bokeh >=3.4.0
  - cartopy ==0.22.0
  - cftime >=1.6.3
  - dask ==2024.2.1
  - datashader >=0.15.0
  - h5py ==3.7.0
  - hdf4 ==4.2.15
  - hdf5 ==1.12.2
  - holoviews >=1.18.0
  - hvplot >=0.9.2
  - netcdf4 ==1.6.3
  - numpy ==1.24.4
  - pandas ==1.5.3
  - panel >=1.4.0
  - param >=2.0.0
  - pyhdf ==0.11.3
  - pyyaml >=6.0.1
  - scipy ==1.13.0
  - xarray ==0.21.1
  - pydap ==3.4.0
  - networkx >=3.1
  - zarr ==2.13.3
  - pygrib
  - pyviz_comms ==3.0.1
  # for streamlit app
  - streamlit >=1.37.0
  - email-validator >=2.2.0
  - python-dotenv >=1.0.1
  # Testing and development dependencies
  - ipykernel
  - ipython >=8.5.0
  - flit >=3.9.0
  - pytest >=8.0.0
  - pip >=24.2.0
  - furo >=2023.9.10
  - sphinx >=7.0.0
  - sphinx-autobuild >=2024.4.16
  - sphinx-autodoc-typehints
  - sphinx-design
  - conda-forge::scikit-learn=1.5.2
  - pip:
      - sphinx_rtd_theme
      - myst-parser
      - sphinxcontrib-mermaid
      - pytest-cov
      - cfgrib

