inputs:
   - name : /Users/ccruz/data/eviz/merra2/MERRA2_400.inst6_3d_ana_Np.20211123.nc4
     to_plot:
         SLP: xy
         H: yz

for_inputs:
    plot_backend: hvplot

outputs:
    output_dir: /Users/ccruz/scratch/eviz/output/gridded_hvplot
    print_to_file: yes

