inputs:
   - name: https://psl.noaa.gov/repository/entry/get/air.mon.mean.nc?entryid=d3422997-979a-4abb-9bf2-503a80bb647f
     description: Data from NCEP initialized reanalysis
     to_plot:
        air: xt,xy,tx

outputs:
    print_to_file: yes
    print_format: jpg

