inputs:
   - name: https://psl.noaa.gov/thredds/dodsC/Datasets/ncep.reanalysis.derived/surface/air.mon.mean.nc
     description: Data from NCEP initialized reanalysis
     to_plot:
        air: xt,xy,tx

outputs:
    print_to_file: yes
    print_format: jpg

