inputs:
- name: ${HOME}/data/eviz/crest/lstm_for_two_r2.nc
  to_plot:
    sm_obs: xy

outputs:
    output_dir: ${HOME}/scratch/eviz/output/crest
    make_pdf: false
    print_format: png
    print_to_file: yes
    make_gif: yes
    gif_fps: 1
    mpl_style: fivethirtyeight

system_opts:
    archive_web_results: false
    use_mp_pool: false

