inputs:
- name: /Users/ccruz/data/eviz/crest/uncoupled.zarr
  description: Uncoupled Model
  exp_id: uncoupled
  to_plot:
      soil_moisture: xy
- name: /Users/ccruz/data/eviz/crest/mh.zarr
  description: MH Model
  exp_id: mh
  to_plot:
      soil_moisture: xy

for_inputs:
#  plot_backend: hvplot
  overlay:
    ids: uncoupled,mh

outputs:
  output_dir: /Users/ccruz/scratch/eviz/output/crest_zarr_ts
  make_pdf: false
  print_format: png
  print_to_file: yes
#  make_gif: yes
#  gif_fps: 1

system_opts:
  archive_web_results: false
  use_mp_pool: false

