soil_moisture:
  units: m³/m³
  name: Soil Moisture
  xtplot:
    grid: yes
    time_lev: all
  scplot:
    time_lev: 59

  boxplot:
    time_lev: all
    box_color: "red"  # For single experiment

  xyplot:
    time_lev: all
    levels:
      0: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7]
    clevs_prec: 2

    rc_params:
      font.family:  sans-serif 
      font.size: 14
      axes.titlesize: 14
      axes.titlelocation: left
#      figure.facecolor: red
      figure.figsize: [8, 4]  # Aspect ratio 2.0

LE:
  units: W/m²
  name: Latent Heat
  boxplot:
    time_lev: -1
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: -1
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

NEE:
  units: µmolCO₂/m²s
  name: Net Ecosystem Exchange 
  boxplot:
    time_lev: all
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: -1
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

streamflow:
  units: mm
  name: Streamflow
  boxplot:
    time_lev: all
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: -1
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

swe:
  units: in
  name: Snow Water Equivalent
  boxplot:
    time_lev: all
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: -1
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey
