soil_moisture:
  units: m³/m³
  name: Soil Moisture
  
  scplot:
    use_cmap: viridis
    time_lev: all
#    rc_params:
#        scatter.marker: "x"

  boxplot:
    time_lev: -1

  xtplot:
    grid: yes
    time_lev: all

  xyplot:
    line_contours: no
    time_lev: all
    levels:
      0: []
    clevs_prec: 2
    rc_params:
      font.family:  sans-serif 
      font.size: 14
      axes.titlesize: 14
      axes.titlelocation: left
#      figure.facecolor: red
      figure.figsize: [8, 4]  # Aspect ratio 2.0

soil_moisture2:
  units: m³/m³
  name: Soil Moisture
  boxplot:
    time_lev: -1
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: all
    levels:
      0: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7]
    clevs_prec: 2
    rc_params:
      font.family:  sans-serif 
      font.size: 14
      axes.titlesize: 14
      axes.titlelocation: left
#      figure.facecolor: red
      figure.figsize: [8, 4]  # Aspect ratio 2.0

LE:
  units: W/m²
  name: Latent Heat
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: all
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

NEE:
  units: µmolCO₂/m²s
  name: Net Ecosystem Exchange 
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: all
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

streamflow:
  units: mm
  name: Streamflow
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: all
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey

swe:
  units: in
  name: Snow Water Equivalent
  xtplot:
    grid: yes
    time_lev: all
  xyplot:
    time_lev: all
    levels:
      0: []
    rc_params:
      font.family:  sans-serif 
      font.size: 20
      axes.titlesize: 18
      axes.titlelocation: left
      figure.facecolor: grey
