inputs:
- name: ${HOME}/data/eviz/crest/vizzy/uncoupled_output.zarr
  description: Uncoupled
  exp_id: uncoupled
  to_plot:
      soil_moisture: box
#      NEE: box
#      LE: box
#      swe: box
#      streamflow: box

- name: ${HOME}/data/eviz/crest/vizzy/coupled_output.zarr
  description: Coupled
  exp_id: coupled
  to_plot:
      soil_moisture: box
#      NEE: box
#      LE: box
#      swe: box
#      streamflow: box

- name: ${HOME}/data/eviz/crest/vizzy/multihead_output.zarr
  description: Multihead
  exp_id: mh
  to_plot:
      soil_moisture: box
#      NEE: box
#      LE: box
#      swe: box
#      streamflow: box

for_inputs:
    plot_backend: hvplot
    overlay:
      ids: uncoupled,coupled,mh
      box_colors: blue,green,orange
      add_legend: no

outputs:
  output_dir: ${HOME}/scratch/eviz/output/crest_box
  make_pdf: false
  print_format: png
  print_to_file: yes

