inputs:
   - name         : GEOS-CF.v01.rpl.chm_tavg_1hr_g1440x721_p40.20171003_*.nc4
     location     : /Users/ccruz/data/eviz/cf
     exp_name    : GEOS-CF v1 Spinup
     description : test1
     to_plot       :
        SLP: xy
        O3: yz,xy
        NO2: yz
        CO: yz
        SO2: yz
        PM25_RH35_GCC: yz
     ignore: Var_

outputs:
    print_to_file: yes
    print_format: png
    make_pdf: no
    print_basic_stats: yes

system_opts:
    use_mp_pool: no
    archive_web_results: no
