inputs:
   - name         : wrfout_d01_2015-07-11_12:00:00
     location     : ${HOME}/data/eviz/wrf
     exp_name: nu-wrf-noahmp
     exp_id: nu-wrf-noahmp
     to_plot:
       TSK: xy
       ALBEDO: xy
       TSLB: xy
       SMOIS: xy
       HFX: xy
       LH: xy
       EMISS: xy
       QFX: xy
       GRDFLX: xy
       SWDOWN: xy
       T2: xy
       Q2: xy

outputs:
    output_dir: ${HOME}/scratch/eviz/output/wrf
    print_to_file: yes

system_opts:
    use_mp_pool: no
    archive_web_results: no

#dark_background
#fivethirtyeight
#seaborn-v0_8
#eviz/lib/templates/hurricane.mplstyle

