inputs:
   - name         : wrfout_d01_2015-07-11_12:00:00
     location     : ${HOME}/data/eviz/wrf
     description: NUWRF (NoahMP) output
     exp_id: nu-wrf-noahmp
     to_plot:
       T2: box

outputs:
    output_dir: ${HOME}/scratch/eviz/output/wrf_compare
    print_to_file: yes


system_opts:
    use_mp_pool: no
    archive_web_results: no



#dark_background
#fivethirtyeight
#seaborn-v0_8
#eviz/lib/templates/hurricane.mplstyle
