inputs:
   - name         : wrfout_d01_2015-07-11_12:00:00
     location     : ${HOME}/data/eviz/wrf
     exp_name: nu-wrf-noahmp
     exp_id: nu-wrf-noahmp
     to_plot:
         Q2: xt
  
   - name         : wrfout_d01_2015-07-11_12:00:00.wrf-arw-nmp
     location     : ${HOME}/data/eviz/wrf
     exp_name: wrf-noahmp
     exp_id: wrf-noahmp
     to_plot:
        Q2: xt
  
   - name         : wrfout_d01_2015-07-11_12:00:00.wrf-arw
     location     : ${HOME}/data/eviz/wrf
     exp_name: wrf-arw
     exp_id: wrf-arw
     to_plot:
        Q2: xt

for_inputs:
    overlay:
      ids: nu-wrf-noahmp,wrf-noahmp,wrf-arw
#    compare:
#      ids: nu-wrf-noahmp,wrf-noahmp

outputs:
    output_dir: ${HOME}/scratch/eviz/output/wrf_compare
    print_to_file: yes


system_opts:
    use_mp_pool: no
    archive_web_results: no



#dark_background
#fivethirtyeight
#seaborn-v0_8
#eviz/lib/templates/hurricane.mplstyle
