TSK:
    xyplot:
        time_lev: all
        levels:
            0:
        contours: [275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325]

RI_SEPA:
    name: Precipitation rate
    xyplot:
        line_contours: false
        cmap: PuBu
#        cmap_set_over: white
#        cmap_set_under: white
        time_lev: all
        levels:
#            0: [0,10,20,30,40,50,60,70,80,90,100]
            0: [0,1,2,3,4,5,10,20,30,40,50]

RAINC:
    name: Accumulated Total Cumulus Precipitation
    xyplot:
        line_contours: false
        cmap: PuBu
        time_lev: all
        levels:
            0: [0, 20, 40, 60, 80, 100, 120, 140, 160]
#[0, 5, 10, 25, 40, 55, 70, 85, 100, 115, 130]

T2:
    name: Surface Temperature
    units: C
    xyplot:
        line_contours: false
        cmap: coolwarm
#        cmap_set_over: white
#        cmap_set_under: white
        time_lev: all
        levels:
            0: [18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]

Q2:
    xyplot:
        time_lev: 4
        levels:
            0:
#    name: Surface Moisture
#    xyplot:
#        cbar_sci_notation: True 
#        line_contours: false
#        cmap: GnBu
#        time_lev: all
#        levels:
#            0: [0.015, 0.0175, 0.020, 0.021, 0.0215, 0.022, 0.0225, 0.023, 0.0235, 0.024]
#[0, 0.001, 0.005, 0.01, 0.012, 0.014, 0.016, 0.018, 0.02, 0.03, 0.05]

PSFC:
    name: Surface Pressure
    unitconversion: 1e-2
    units: mb
    xyplot:
        line_contours: false
        cmap: Spectral
        cmap_set_over: white
        cmap_set_under: white
        time_lev: all
        levels:
            0: [900, 910, 920, 930, 940, 950, 960, 970, 975, 980, 985, 990, 995]


