inputs:
   - name         : RefD1.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location     : ${HOME}/data/eviz/ccm
     exp_name     : RefD1
     exp_id       : RefD1
     description  : RefD1 Annual
     to_plot:
       co_25: xy,yz
       aoa: xy,yz
     ignore: Var_
     
   - name         : bench_10-17-6_gmi_free_c180_72lev.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location     : ${HOME}/data/eviz/ccm
     exp_name     : bench
     exp_id       : bench
     description  : bench Annual
     to_plot:
       co_25: xy,yz
       aoa: yz,xy
     ignore: Var_

outputs:
    output_dir: ${HOME}/scratch/eviz/output/ccm
    print_to_file: yes
    print_format: png
    make_pdf: no
    print_basic_stats: yes
    # New visualization options
    visualization:
      backend: matplotlib
      style: default
      dpi: 300
      colormap: viridis
      contour_levels: 20
      add_colorbar: true
      add_title: true
      add_grid: true

system_opts:
    use_mp_pool: no
    archive_web_results: no
    # New caching options
    caching:
      enabled: true
      cache_dir: /tmp/eviz_cache
      max_size_mb: 1000
      ttl_hours: 24
