inputs:
   - name         : RefD1.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location     : ${HOME}/data/eviz/ccm
     exp_name     : RefD1
     exp_id       : RefD1
     description  : RefD1 Annual
     to_plot:
       co_25: xy,yz
       aoa: xy,yz
     ignore: Var_
     
   - name         : bench_10-17-6_gmi_free_c180_72lev.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location     : ${HOME}/data/eviz/ccm
     exp_name     : bench
     exp_id       : bench
     description  : bench Annual
     to_plot:
       co_25: xy,yz
       aoa: yz,xy
     ignore: Var_

for_inputs:
    airmass_file_name: ${HOME}/data/eviz/ccm/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4
    airmass_field_name: AIRMASS
# Use URL
#    airmass_url: https://portal.nccs.nasa.gov/datashare/astg/eviz/airmass/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4

outputs:
    output_dir: ${HOME}/scratch/eviz/output/ccm
    print_to_file: yes
    print_format: png
    make_pdf: no
    print_basic_stats: yes

system_opts:
    use_mp_pool: no
    archive_web_results: no
