inputs:
   - name         : bench_10-17-6_gmi_free_c180_72lev.tavg24_3d_dat_Np.monthly.clim.JJA.nc4
     location     : /Users/ccruz/data/eviz/ccm
     exp_name    : BenchmarkFc180
     exp_id    : BenchmarkFc180
     description : GMI free-running simulation, with GOCART aerosols and TR passive #tracers
     to_plot       :
        aoa: yz
        Be10: yz
        co_25: xy
     ignore: Var_
   - name         : RefD1.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location     : /Users/ccruz/data/eviz/ccm
     exp_name    : RefD1
     exp_id    : RefD1
     to_plot       :
        aoa: yz
        Be10: yz
        co_25: xy
     ignore: Var_

outputs:
    output_dir: /Users/ccruz/scratch/eviz/output/ccm
    print_to_file: yes
    print_format: png
    make_pdf: no
    print_basic_stats: yes

system_opts:
    use_mp_pool: no
    archive_web_results: no

for_inputs:
    compare:
      ids: BenchmarkFc180,RefD1
      extra_diff: ratio
      # Use different colormap for comparison plots
      cmap: coolwarm
#    trop_height:
#      - name: bench_10-17-6_gmi_free_c180_72lev.tavg24_2d_dad_Nx.monthly.clim.JJA.nc4
#        location: /Users/ccruz/data/eviz/ccm
#        # Apply to this experiment
#        exp_name: BenchmarkFc180
#        ## Possibilities: TROPPV (Pa), TROPPT(Pa), TROPPB(Pa)
#        trop_field_name: TROPPB
#    airmass_file_name: /Users/ccruz/data/eviz/ccm/RefD1.tavg24_3d_dac_Np.monthly.clim.ANN.nc4
#    airmass_field_name: AIRMASS

