inputs:
   - name        : bench_10-17-6_gmi_free_c180_72lev.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location    :  /Users/ccruz/data/eviz/ccm
     exp_name    : BenchAnn
     exp_id      : BenchAnn
     description : Benchmark GMI Simulation
     to_plot       :
         co_25: xy,yz
         aoa: yz
         stO3: yz
     ignore: Var_
   - name: RefD2.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location  : /Users/ccruz/data/eviz/ccm
     exp_name  : RefD2ann
     exp_id    : RefD2ann
     description : RedD2ann Simulation
     to_plot   :
         co_25: xy,yz
         aoa: yz
         stO3: yz
     ignore: Var_

for_inputs:
    compare_diff:
      ids: BenchAnn,RefD2ann
      cmap: coolwarm

outputs:
    output_dir: /Users/ccruz/scratch/eviz/output/ccm_compare_3x1
    print_to_file: yes
    print_format: png
    make_pdf: no
#    print_basic_stats: yes
    log_file: false
    add_logo: true

system_opts:
    use_mp_pool: no
    archive_web_results: no

