inputs:
   - name        : bench_10-17-6_gmi_free_c180_72lev.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location    :  ${HOME}/data/eviz/ccm
     exp_name    : BenchAnn
     exp_id      : BenchAnn
     description : Benchmark GMI Simulation
     to_plot       :
         aoa: yz
     ignore: Var_
   - name: RefD2.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location  : ${HOME}/data/eviz/ccm
     exp_name  : RefD2ann
     exp_id    : RefD2ann
     description : RedD2ann Simulation
     to_plot   :
         aoa: yz
     ignore: Var_
   - name: RefD1.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location  : ${HOME}/data/eviz/ccm
     exp_name  : RefD1ann
     exp_id    : RefD1ann
     description : RedD1ann Simulation
     to_plot   :
         aoa: yz
     ignore: Var_
   
for_inputs:
    overlay:
      ids: BenchAnn,RefD2ann,RefD1ann

outputs:
    output_dir: ${HOME}/scratch/eviz/output/ccm_overlay
    print_to_file: yes
    print_format: png
    make_pdf: no
#    print_basic_stats: yes
    log_file: false
    add_logo: true

system_opts:
    use_mp_pool: no
    archive_web_results: no

