EMSOILNOX:
    units: mol/mol
    xyplot:
        cbar_sci_notation: yes
#        variation_threshold: 1e-12
        line_contours: no
        levels:
            0: []

stO3:
    units: DU
    xyplot:
        zsum: yes 
        levels:
            0: []
        diff_20: [-100.0, -80.0, -60.0, -40.0, -20.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 40.0, 60.0, 80.0, 100.0]
        diff_200: [-100.0, -80.0, -60.0, -40.0, -20.0, -15.0, -10.0, -5.0, 0.0, 5.0, 10.0, 15.0, 20.0, 40.0, 60.0, 80.0, 100.0]
        diff_500: [-10.0, -8.0, -6.0, -4.0, -2.0, -1.0, 0.0, 1.0, 2.0, 4.0, 6.0, 8.0, 10.0]
        diff_1000: [-12.0, -10.0, -8.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 8.0, 10.0, 12.0]

ColumnAmountO3:
    name: O3 Total Column
    xyplot:
        levels:
            0: []

