inputs:
   - name        : RefD2.tavg24_3d_dat_Np.monthly.clim.JJA.nc4
     location    :  /Users/ccruz/data/eviz/ccm
     exp_name    : RefD2jja
     exp_id      : RefD2jja
     description : RedD2 Simulation
     to_plot       :
         Be10: yz
         aoa: yz
         aoa_bl: yz
     ignore: Var_
   - name: RefD2.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location  : /Users/ccruz/data/eviz/ccm
     exp_name  : RefD2ann
     exp_id    : RefD2ann
     description : RedD2ann Simulation
     to_plot   :
         Be10: yz
         aoa: yz
         aoa_bl: yz
     ignore: Var_

for_inputs:
    compare_diff:
      ids: RefD2jja,RefD2ann
      cmap: coolwarm
      extra_diff: ratio

outputs:
    output_dir: /Users/ccruz/scratch/eviz/output/ccm_compare_2x2
    print_to_file: yes
    print_format: png
    make_pdf: no
#    print_basic_stats: yes
    log_file: false
    add_logo: true

system_opts:
    use_mp_pool: no
    archive_web_results: no

