inputs:
   - name: RefD2.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     reader   : netcdf
     location  : ${HOME}/data/eviz/ccm
     exp_id    : RefD2ann
     description : RedD2ann Simulation
     to_plot   :
         stO3: xy
     ignore: Var_

   - name: RefD2.tavg24_2d_emi_Nx.monthly.clim.ANN.nc4
     reader   : netcdf
     location  : ${HOME}/data/eviz/ccm
     description : 
     to_plot   :
         EMSOILNOX: xy

   - name     :  OMI-Aura_L3-OMTO3d_2018m1001_v003-2019m0802t075840.he5.nc4
     reader: hdf5
     location : ${HOME}/data/eviz/omi
     to_plot  :
         ColumnAmountO3: xy

for_inputs:
    airmass_file_name: ${HOME}/data/eviz/ccm/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4
    airmass_field_name: AIRMASS
# Use URL
#    airmass_url: https://portal.nccs.nasa.gov/datashare/astg/eviz/airmass/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4

outputs:
    output_dir: ${HOME}/scratch/eviz/output/ccm_omi
    print_to_file: yes
    print_format: png
    make_pdf: no

system_opts:
    use_mp_pool: no
    archive_web_results: no


