inputs:
   - name: RefD2.tavg24_3d_dat_Np.monthly.clim.ANN.nc4
     location: /Users/ccruz/data/eviz/merra2
     exp_name  :  RefD2_ANN
     exp_id    : RefD2
     to_plot:
        stO3: xy

   - name: OMI-Aura_L3-OMTO3d_2022.ANN.nc4
     location  : /Users/ccruz/data/eviz/satellite/omiO3_2022
     format: hdf5
     exp_name  : OMI-Aura
     exp_id    : OMI-Aura
     description : OMI-Aura_L3 O3 Column Data
     to_plot   :
         ColumnAmountO3: xy

outputs:
    output_dir: ${HOME}/scratch/eviz/output/comparisons
    print_to_file: yes
    print_format: png
    make_pdf: no
    print_basic_stats: yes
    log_file: false

system_opts:
    use_mp_pool: no
    archive_web_results: no


for_inputs:
    # Personal copy
    airmass_file_name: /Users/ccruz/data/eviz/ccm/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4
    # On DISCOVER
    airmass_file_name: /css/astg/eviz/airmass/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4
    # URL used on OSS or AWS
    airmass_url: https://portal.nccs.nasa.gov/datashare/astg/eviz/airmass/RefD2.tavg24_3d_dac_Np.AIRMASS.ANN.nc4
    airmass_field_name: AIRMASS
#    compare:
#      ids: MERRA2,OMI-Aura
#      cmap: coolwarm
#      extra_diff: ratio
