# Dimension names in each supported  data source (AKA model)
# Notes:
# (1) The key values (i.e. xc, yc, ...)  represent the internal
#     Eviz coordinate names while the model values are all the
#     Eviz-recognized coordinate names for that particular source
# (2)  A gridded model is common model often stored in NetCDF files

# x-coordinate name: model
xc:
    geos: lon
    ccm: lon
    cf: lon
    gmi: longitude_dim
    grib: lon,longitude,im
    gridded: lon,longitude,im,Longitude
    crest: lon,longitude,im
    airnow: Longitude
    omi: Longitude,longitude,lon
    wrf:
        dim: west_east
        coords: XLONG,XLONG_U,XLONG_V
    lis:
        dim: east_west
        coords: lon
    test:
        dim: lon
        coords: lon
    spacetime: lon
    timeseries: time

# y-coordinate name: model
yc:
    geos: lat
    ccm: lat
    cf: lat
    gmi: latitude_dim
    grib: lat,latitude,jm
    gridded: lat,latitude,jm,Latitude
    crest: lat,latitude,jm
    airnow: Latitude
    omi: Latitude,latitude,lat
    wrf:
        dim: south_north
        coords: XLAT,XLAT_U,XLAT_V
    lis:
        dim: north_south
        coords: lat
    test:
        dim: lat
        coords: lat
    spacetime: lat
    timeseries: location

# z-coordinate name: model
zc:
    geos: lev
    ccm: lev
    cf: lev
    gmi: eta_dim
    grib: lev,level,levels,plev,lm,eta_dim
    gridded: lev,level,levels,plev,lm,eta_dim
    crest: lev,level,levels,plev,lm,eta_dim
    airnow: NA
    omi: NA
    wrf:
        dim: bottom_top,bottom_top_stag,soil_layers,soil_layers_stag
        coords: VERT
    lis:
        dim: RelSMC_profiles,SoilTemp_profiles,SoilMoist_profiles,SmLiqFrac_profiles
    test: lev
    spacetime: lev

# time-coordinate name: model
tc:
    geos: time
    ccm: time
    cf: time
    gmi: rec_dim
    grib: time,Time
    gridded: time,rec_dim,ntimemax
    crest: time,datetime,Time
    airnow: time
    omi: Time
    wrf:
        dim: Time
        coords: XTIME
    lis:
        dim: time
        coords: time
    test: time
    spacetime: time

# chemical species name
spec:
    gmi: species_dim

