# recreates:
# https://docs.xarray.dev/en/stable/examples/ERA5-GRIB-example.html
inputs:
   - name: era5-2mt-2019-03-uk.grib
     location: ${HOME}/data/eviz/era5
     format: grib
     to_plot:
        t2m: xy,xt

outputs:
    output_dir: ${HOME}/scratch/eviz/output/grib
    print_to_file: yes
    print_format: jpg

