# GEOS field-specific configurations.
# ---------------------------------
O3:
    unitconversion: 1000000000.0
    units: ppb
    yzplot:
        cmap: coolwarm
        zrange: [1000, 1]
        contours: []
        diffcontours: []
    xyplot:
        cmap: coolwarm
        levels:
            100: []
        diff_100: []
    xtplot:
        times: all
        grid: yes
    txplot:
        cmap: coolwarm
        times: all  # default time=0, or specify range [tmin, tmax], or all
        grid: yes   # plot grid (default is no)   # plot grid (default is no)
        contours: [20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]

T:
    xyplot:
        levels:
            500: []
    yzplot:
#        profile_dim: yc
        zrange: [1000, 0.1]
        zscale: log
        contours: []

SLP:
    unitconversion: 0.01
    units: mb
    xyplot:
        levels:
            0: []
    xtplot:
        times: all

TSURF:
    xyplot:
        levels:
            0: []
    xtplot:
        times: all
        grid: yes

TSOIL1:
    xyplot:
        levels:
            0: []
    xtplot:
        times: all
        grid: yes

RUNOFF:
    xyplot:
        levels:
            0: []
    xtplot:
        times: all
        grid: yes

U10M:
    xtplot:
        times: all
        grid: yes

RAINOCN:
    xtplot:
        times: all
        grid: yes
    txplot:   # hovmoller plot
        times: all  # default time=0, or specify range [tmin, tmax], or all
        grid: yes   # plot grid (default is no)
        xrange: [-25, 50]
        yrange: [0, 40]
        # Contour levels are OPTIONAL
        contours: []
        mean_type: month
        space_dim: lat   # lat, lon, or lev
        torder: rev   # reverse time-axis ordering (default increases bottom-to-top)

TAUXWTR:
    xyplot:
        tave: yes
        levels:
            0: []
    xtplot:
        times: all
        grid: yes

TAUYWTR:
    xyplot:
        levels:
            0: []
    xtplot:
        times: all
        grid: yes

FRSEAICE:
    name: Sea ice cover
    polarplot:
        pole: north
        grid: yes
        cmap: BuPu
        boundary: yes
        levels:
            0: []

ta:
    unitconversion: 1
    xtplot:
        times: all  # default time=0, or specify range [tmin, tmax], or all
        grid: yes   # plot grid (default is no)   # plot grid (default is no)
        mean_type: point_sel
        clima: year  # year, season, month
        point_sel: [0.5, 7.5]   # lon, lat
        area_sel: [-10.5, 10.5, 5, 25]  # lon1, lon2, lat1, lat2  # default delta = 0.5
        level: 50000
    txplot:
        mean_type: xc
        trange: [2019-01-01, 2020-01-01] # default time=0, or specify range tmin,tmax, or all
        xrange: [0, 360]
        yrange: [0, 40]
        space_dim: lat   # lat, lon, or lev
#        torder: rev   # reverse time-axis ordering (default increases bottom-to-top)
    xyplot:
        levels:
            85000: [210,225,235,245,255,270,280,290,295,300,305,310,315]
        diff_85000: [-5.0,-2.5,-1.25,-0.75,-0.5,-0.25,-0.1,0.1,0.25,0.5,0.75,1.25,2.5,5.0]


