inputs:
   - name     : /Users/ccruz/data/eviz/airnow/HourlyAQObs*
     description: 25 Î¼m particulate matter
     reader   : csv
     to_plot  :
        PM25: sc

#for_inputs:
#    plot_backend: hvplot

outputs:
    output_dir: /Users/ccruz/scratch/eviz/output/airnow
    print_to_file: yes
 
