PM25:
    unitconversion: 1
    units: ppb
    scplot:
        cmap: BuPu
        extent: conus
        projection: lambert
        rc_params:
            font.size: 12
            axes.titlesize: 16
            scatter.marker: "x"
