# ---------------------------------
diff_prop: &DIFF_PROP
    diff_percd: [ -500., -50., -10., -5., -0.5, 0.5, 5., 10., 50., 500. ]
    diff_percc: [ -500., -50., -10., -5., -0.5, 0.5, 5., 10., 50., 500. ]
    diff_ratio: [ .5,.6,.7,.8,.9,1.0,1.1,1.2,1.3,1.4,1.5 ]